version: '3.8'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  model-training:
    build: 
      context: https://github.com/project-ia-modelisation/model-training.git
      dockerfile: DockerFile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - mynetwork

  model-serving:
    build:
      context: https://github.com/project-ia-modelisation/model-serving.git
      dockerfile: DockerFile
    ports:
      - "5000:5000"
    depends_on:
      - model-training
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - mynetwork
  
  deployment:
    build:
      context: https://github.com/project-ia-modelisation/deployment.git
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    depends_on:
      - model-serving
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - mynetwork
  
  experiments:
    build:
      context: https://github.com/project-ia-modelisation/experiments.git
      dockerfile: DockerFile
    depends_on:
      - model-training
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - mynetwork
  
  data-processing:
    build:
      context: https://github.com/project-ia-modelisation/data-processing.git
      dockerfile: DockerFile
    ports:
      - "5001:5000"
    depends_on:
      - model-training
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
